### ISSUE TITLE
客户端连接RNacos服务器报错

### ISSUE THREAD

**Issue by Zhao-Michael** [nacos-group/r-nacos#176]
fail: Nacos.V2.Config.NacosConfigService[0]
      [NACOS ConnectException] currentServerAddr: http://xxxxxxxxxxxxxx:8848, httpCode: BadGateway
fail: Nacos.V2.Config.NacosConfigService[0]
      [NACOS ConnectException] currentServerAddr: http://xxxxxxxxxxxxxx:8848, httpCode: BadGateway
fail: Nacos.V2.Config.NacosConfigService[0]
      [NACOS ConnectException] currentServerAddr: http://xxxxxxxxxxxxxx:8848, httpCode: BadGateway
fail: Nacos.V2.Config.NacosConfigService[0]
      [NACOS ConnectException] currentServerAddr: http://xxxxxxxxxxxxxx:8848, httpCode: BadGateway
fail: Nacos.V2.Config.NacosConfigService[0]
      [fixed-xxxxxxxxxxxxxx_8848-gk50] [check-update] get changed dataId exception
      System.Exception: [NACOS HTTP-POST] The maximum number of tolerable server reconnection errors has been reached
         at Nacos.V2.Config.Http.ServerHttpAgent.HttpRequest(String path, Dictionary`2 headers, Dictionary`2 paramValues, String encoding, Int64 readTimeoutMs, HttpMethod method)
         at Nacos.V2.Config.Http.ServerHttpAgent.HttpPost(String path, Dictionary`2 headers, Dictionary`2 paramValues, String encoding, Int64 readTimeoutMs)
         at Nacos.V2.Config.Impl.ConfigHttpTransportClient.CheckUpdateConfigStr(String probeUpdateString, Boolean isInitializingCacheList)
fail: Nacos.V2.Config.NacosConfigService[0]
      longPolling error
      System.Exception: [NACOS HTTP-POST] The maximum number of tolerable server reconnection errors has been reached
         at Nacos.V2.Config.Http.ServerHttpAgent.HttpRequest(String path, Dictionary`2 headers, Dictionary`2 paramValues, String encoding, Int64 readTimeoutMs, HttpMethod method)
         at Nacos.V2.Config.Http.ServerHttpAgent.HttpPost(String path, Dictionary`2 headers, Dictionary`2 paramValues, String encoding, Int64 readTimeoutMs)
         at Nacos.V2.Config.Impl.ConfigHttpTransportClient.CheckUpdateConfigStr(String probeUpdateString, Boolean isInitializingCacheList)
         at Nacos.V2.Config.Impl.ConfigHttpTransportClient.CheckUpdateDataIds(List`1 cacheDatas, List`1 inInitializingCacheList)
         at Nacos.V2.Config.Impl.ConfigHttpTransportClient.<LongPolling>b__33_0(Object x)

**Comment by heqingpan** [comment]
服务端和客户端分别是什么版本？

服务端有什么报错内容吗？

通过域名访问后，对应的8848,8948端口是否都配置正确？（如果服务端没有对应日志，可以先在本地直接127.0.0.1:8848测试，先确认是否是网络配置问题。）

**Comment by Zhao-Michael** [comment]
客户端：   nacos-sdk-csharp 1.3.9
服务端版本：v0.6.0

我都更新一下试试

**Comment by heqingpan** [comment]
v0.6.5版本有兼容相关的更新，你可以更新到新版本后再看看有没有问题。

v0.6.5的部分更新说明
优化：兼容nacos-sdk-csharp中的grpc发布配置接口；https://github.com/nacos-group/r-nacos/issues/162

**Comment by Zhao-Michael** [comment]
升级还是偶尔会发生这样的错误，一般重启client就不复现了

**Comment by heqingpan** [comment]
发生这个错误时服务端有打印什么错误信息吗？

这个偶尔发生的频率大概是多久出现一次？

**Comment by Zhao-Michael** [comment]
没有发现什么特别的信息，出现概率很低，如果我找到了稳定复现的步骤，我在重开这个issue, 谢谢

**Comment by Zhao-Michael** [comment]
https://www.cnblogs.com/yangtsecode/p/12023536.html
